In [11]:
import pandas as pd

In [23]:
df = pd.read_csv('./result_qpp_union/bi-directional/mt5_3.csv')
df_o = df.copy()
df = df[((df.alpha==0)|(df.alpha==0.5)|(df.alpha==1))&(df.window_size==10)]

In [25]:
df_o.sort_values(by=['tau'], ascending=False)

,retriever,k,qpp_method,window_size,alpha,r,p1(r),tau,p1(tau),num_of_queries,with_0shot_posterior
2857,mt5,3,bertQPP,15,0.60,0.401526,0.000046,0.300687,0.000013,97,True
3067,mt5,3,bertQPP,16,0.60,0.402483,0.000044,0.299828,0.000014,97,True
3057,mt5,3,bertQPP,16,0.55,0.402735,0.000043,0.299399,0.000014,97,True
2847,mt5,3,bertQPP,15,0.55,0.401833,0.000045,0.297680,0.000016,97,True
2637,mt5,3,bertQPP,14,0.55,0.399858,0.000050,0.295962,0.000017,97,True
...,...,...,...,...,...,...,...,...,...,...,...
1054,mt5,3,nqc,7,0.00,0.154428,0.130966,-0.079467,0.248844,97,False
2104,mt5,3,nqc,12,0.00,0.154428,0.130966,-0.079467,0.248844,97,False
1264,mt5,3,nqc,8,0.00,0.154428,0.130966,-0.079467,0.248844,97,False
214,mt5,3,nqc,3,0.00,0.154428,0.130966,-0.079467,0.248844,97,False
3150,mt5,3,0shot_pos,16,1.00,-0.249340,0.013781,-0.186426,0.006825,97,True

In [17]:
df[(df.alpha==0.5)&(df.with_0shot_posterior==True)]

,retriever,k,qpp_method,window_size,alpha,r,p1(r),tau,p1(tau),num_of_queries,with_0shot_posterior
1781,mt5,3,spatial,10,0.5,0.286563,0.004432,0.211770,0.002119,97,True
1783,mt5,3,a_ratio,10,0.5,0.176268,0.084152,0.072165,0.295010,97,True
1785,mt5,3,nqc,10,0.5,0.331278,0.000918,0.229381,0.000873,97,True
1787,mt5,3,bertQPP,10,0.5,0.374813,0.000155,0.271907,0.000080,97,True
1789,mt5,3,bertQPP(QV),10,0.5,0.351958,0.000407,0.253436,0.000235,97,True

In [18]:
df[(df.alpha==0.5)&(df.with_0shot_posterior==False)]

,retriever,k,qpp_method,window_size,alpha,r,p1(r),tau,p1(tau),num_of_queries,with_0shot_posterior
1780,mt5,3,spatial,10,0.5,0.325561,0.001138,0.208333,0.002502,97,False
1782,mt5,3,a_ratio,10,0.5,0.123754,0.227168,0.012887,0.851661,97,False
1784,mt5,3,nqc,10,0.5,0.294562,0.003403,0.199742,0.003750,97,False
1786,mt5,3,bertQPP,10,0.5,0.344837,0.000542,0.236254,0.000607,97,False
1788,mt5,3,bertQPP(QV),10,0.5,0.309892,0.002009,0.210481,0.002256,97,False

In [26]:
df[(df.alpha==0)&(df.with_0shot_posterior==True)]

,retriever,k,qpp_method,window_size,alpha,r,p1(r),tau,p1(tau),num_of_queries,with_0shot_posterior
1681,mt5,3,spatial,10,0.0,0.265354,0.008619,0.202320,0.003326,97,True
1683,mt5,3,a_ratio,10,0.0,0.149700,0.143326,0.036512,0.596229,97,True
1685,mt5,3,nqc,10,0.0,0.154727,0.130215,-0.073454,0.286471,97,True
1687,mt5,3,bertQPP,10,0.0,0.260262,0.010036,0.214347,0.001868,97,True
1689,mt5,3,bertQPP(QV),10,0.0,0.210732,0.038276,0.173540,0.011794,97,True

In [27]:
df[(df.alpha==0)&(df.with_0shot_posterior==False)]

,retriever,k,qpp_method,window_size,alpha,r,p1(r),tau,p1(tau),num_of_queries,with_0shot_posterior
1680,mt5,3,spatial,10,0.0,0.290285,0.003923,0.180842,0.008685,97,False
1682,mt5,3,a_ratio,10,0.0,0.098037,0.339404,-0.013316,0.846777,97,False
1684,mt5,3,nqc,10,0.0,0.154428,0.130966,-0.079467,0.248844,97,False
1686,mt5,3,bertQPP,10,0.0,0.207361,0.041550,0.168385,0.014547,97,False
1688,mt5,3,bertQPP(QV),10,0.0,0.142561,0.163624,0.119845,0.082019,97,False

In [29]:
df[(df.alpha==1)&(df.qpp_method=='nqc')]

,retriever,k,qpp_method,window_size,alpha,r,p1(r),tau,p1(tau),num_of_queries,with_0shot_posterior
1884,mt5,3,nqc,10,1.0,0.276963,0.006026,0.182990,0.007922,97,False
1885,mt5,3,nqc,10,1.0,0.314823,0.001685,0.213918,0.001908,97,True

In [19]:
df[df.with_0shot_posterior==False].sort_values(by=['tau'], ascending=False).head(5)

,retriever,k,qpp_method,window_size,alpha,r,p1(r),tau,p1(tau),num_of_queries,with_0shot_posterior
1786,mt5,3,bertQPP,10,0.5,0.344837,0.000542,0.236254,0.000607,97,False
1788,mt5,3,bertQPP(QV),10,0.5,0.309892,0.002009,0.210481,0.002256,97,False
1780,mt5,3,spatial,10,0.5,0.325561,0.001138,0.208333,0.002502,97,False
1784,mt5,3,nqc,10,0.5,0.294562,0.003403,0.199742,0.003750,97,False
1880,mt5,3,spatial,10,1.0,0.276963,0.006026,0.182990,0.007922,97,False

In [20]:
df[df.with_0shot_posterior].sort_values(by=['tau'], ascending=False).head(5)

,retriever,k,qpp_method,window_size,alpha,r,p1(r),tau,p1(tau),num_of_queries,with_0shot_posterior
1787,mt5,3,bertQPP,10,0.5,0.374813,0.000155,0.271907,0.000080,97,True
1789,mt5,3,bertQPP(QV),10,0.5,0.351958,0.000407,0.253436,0.000235,97,True
1785,mt5,3,nqc,10,0.5,0.331278,0.000918,0.229381,0.000873,97,True
1687,mt5,3,bertQPP,10,0.0,0.260262,0.010036,0.214347,0.001868,97,True
1881,mt5,3,spatial,10,1.0,0.314823,0.001685,0.213918,0.001908,97,True

In [21]:
df[(df.alpha==0)&(df.window_size==10)&(df.with_0shot_posterior==False)]

,retriever,k,qpp_method,window_size,alpha,r,p1(r),tau,p1(tau),num_of_queries,with_0shot_posterior
1680,mt5,3,spatial,10,0.0,0.290285,0.003923,0.180842,0.008685,97,False
1682,mt5,3,a_ratio,10,0.0,0.098037,0.339404,-0.013316,0.846777,97,False
1684,mt5,3,nqc,10,0.0,0.154428,0.130966,-0.079467,0.248844,97,False
1686,mt5,3,bertQPP,10,0.0,0.207361,0.041550,0.168385,0.014547,97,False
1688,mt5,3,bertQPP(QV),10,0.0,0.142561,0.163624,0.119845,0.082019,97,False

In [22]:
df[(df.alpha==0)&(df.window_size==2)&(df.with_0shot_posterior)]

Empty DataFrame
Columns: [retriever, k, qpp_method, window_size, alpha, r, p1(r), tau, p1(tau), num_of_queries, with_0shot_posterior]
Index: []

In [9]:
df[(df.alpha==1)&(df.qpp_method=='spatial')&(df.with_0shot_posterior==False)]

,retriever,k,qpp_method,window_size,alpha,r,p1(r),tau,p1(tau),num_of_queries,with_0shot_posterior
1880,mt5,3,spatial,10,1.0,0.251897,0.01281,0.123711,0.072623,97,False

In [10]:
df[(df.alpha==1)&(df.qpp_method=='spatial')&(df.with_0shot_posterior)]

,retriever,k,qpp_method,window_size,alpha,r,p1(r),tau,p1(tau),num_of_queries,with_0shot_posterior
1881,mt5,3,spatial,10,1.0,0.293448,0.003532,0.147766,0.032012,97,True