In [1]:
import pandas as pd

In [4]:
df = pd.read_csv('./result_qpp_union/bm25_3.csv')
df = df[((df.alpha==0)|(df.alpha==0.5)|(df.alpha==1))&(df.window_size==10)]

In [5]:
df[df.alpha==0].sort_values(by=['tau'], ascending=False)

,retriever,k,qpp_method,window_size,alpha,r,p1(r),tau,p1(tau),num_of_queries,with_0shot_posterior
1683,bm25,3,a_ratio,10,0.0,0.438169,0.000007,0.292526,0.000022,97,True
1681,bm25,3,spatial,10,0.0,0.354755,0.000363,0.279639,0.000050,97,True
1687,bm25,3,bertQPP,10,0.0,0.329410,0.000985,0.224656,0.001114,97,True
1689,bm25,3,bertQPP(QV),10,0.0,0.342484,0.000595,0.220790,0.001356,97,True
1680,bm25,3,spatial,10,0.0,0.384525,0.000101,0.219931,0.001416,97,False
1686,bm25,3,bertQPP,10,0.0,0.255573,0.011518,0.186856,0.006698,97,False
1688,bm25,3,bertQPP(QV),10,0.0,0.247476,0.014529,0.185567,0.007086,97,False
1682,bm25,3,a_ratio,10,0.0,0.313620,0.001760,0.120704,0.079850,97,False
1685,bm25,3,nqc,10,0.0,0.122510,0.231911,0.045962,0.504796,97,True
1684,bm25,3,nqc,10,0.0,0.015030,0.883825,-0.023625,0.731725,97,False

In [13]:
df[(df.alpha==0.5)&(df.with_0shot_posterior==True)]

,retriever,k,qpp_method,window_size,alpha,r,p1(r),tau,p1(tau),num_of_queries,with_0shot_posterior
1781,bm25,3,spatial,10,0.5,0.360167,0.000290,0.288660,0.000028,97,True
1783,bm25,3,a_ratio,10,0.5,0.439018,0.000007,0.308849,0.000007,97,True
1785,bm25,3,nqc,10,0.5,0.137730,0.178522,0.062285,0.366086,97,True
1787,bm25,3,bertQPP,10,0.5,0.398588,0.000053,0.233247,0.000713,97,True
1789,bm25,3,bertQPP(QV),10,0.5,0.408793,0.000032,0.246134,0.000355,97,True

In [7]:
df[df.with_0shot_posterior==False].sort_values(by=['tau'], ascending=False).head(5)

,retriever,k,qpp_method,window_size,alpha,r,p1(r),tau,p1(tau),num_of_queries,with_0shot_posterior
1680,bm25,3,spatial,10,0.0,0.384525,0.000101,0.219931,0.001416,97,False
1780,bm25,3,spatial,10,0.5,0.334352,0.000816,0.201460,0.003462,97,False
1786,bm25,3,bertQPP,10,0.5,0.316656,0.001578,0.192010,0.005332,97,False
1788,bm25,3,bertQPP(QV),10,0.5,0.313565,0.001763,0.190292,0.005756,97,False
1686,bm25,3,bertQPP,10,0.0,0.255573,0.011518,0.186856,0.006698,97,False

In [8]:
df[df.with_0shot_posterior].sort_values(by=['tau'], ascending=False).head(5)

,retriever,k,qpp_method,window_size,alpha,r,p1(r),tau,p1(tau),num_of_queries,with_0shot_posterior
1783,bm25,3,a_ratio,10,0.5,0.439018,0.000007,0.308849,0.000007,97,True
1683,bm25,3,a_ratio,10,0.0,0.438169,0.000007,0.292526,0.000022,97,True
1781,bm25,3,spatial,10,0.5,0.360167,0.000290,0.288660,0.000028,97,True
1681,bm25,3,spatial,10,0.0,0.354755,0.000363,0.279639,0.000050,97,True
1789,bm25,3,bertQPP(QV),10,0.5,0.408793,0.000032,0.246134,0.000355,97,True

In [9]:
df[(df.alpha==0)&(df.window_size==10)&(df.with_0shot_posterior==False)]

,retriever,k,qpp_method,window_size,alpha,r,p1(r),tau,p1(tau),num_of_queries,with_0shot_posterior
1680,bm25,3,spatial,10,0.0,0.384525,0.000101,0.219931,0.001416,97,False
1682,bm25,3,a_ratio,10,0.0,0.313620,0.001760,0.120704,0.079850,97,False
1684,bm25,3,nqc,10,0.0,0.015030,0.883825,-0.023625,0.731725,97,False
1686,bm25,3,bertQPP,10,0.0,0.255573,0.011518,0.186856,0.006698,97,False
1688,bm25,3,bertQPP(QV),10,0.0,0.247476,0.014529,0.185567,0.007086,97,False

In [10]:
df[(df.alpha==0)&(df.window_size==2)&(df.with_0shot_posterior)]

Empty DataFrame
Columns: [retriever, k, qpp_method, window_size, alpha, r, p1(r), tau, p1(tau), num_of_queries, with_0shot_posterior]
Index: []

In [11]:
df[(df.alpha==1)&(df.qpp_method=='spatial')&(df.with_0shot_posterior==False)]

,retriever,k,qpp_method,window_size,alpha,r,p1(r),tau,p1(tau),num_of_queries,with_0shot_posterior
1880,bm25,3,spatial,10,1.0,0.182392,0.073761,0.137027,0.046765,97,False

In [12]:
df[(df.alpha==1)&(df.qpp_method=='spatial')&(df.with_0shot_posterior)]

,retriever,k,qpp_method,window_size,alpha,r,p1(r),tau,p1(tau),num_of_queries,with_0shot_posterior
1881,bm25,3,spatial,10,1.0,0.231417,0.022566,0.181701,0.008372,97,True