In [1]:
import pandas as pd

In [10]:
df = pd.read_csv('./result_qpp_union/tct_10.csv')

In [11]:
df.sort_values(by=['tau'], ascending=False).head(5)

,retriever,k,qpp_method,window_size,alpha,r,p1(r),tau,p1(tau),num_of_queries
188,tct,10,bertQPP,2,0.74,0.462407,0.000002,0.317010,0.000004,97
198,tct,10,bertQPP,2,0.78,0.458590,0.000002,0.315292,0.000005,97
203,tct,10,bertQPP,2,0.80,0.454819,0.000003,0.314003,0.000005,97
183,tct,10,bertQPP,2,0.72,0.462424,0.000002,0.314003,0.000005,97
208,tct,10,bertQPP,2,0.82,0.449876,0.000004,0.313574,0.000005,97

In [12]:
df[(df.alpha==0)&(df.window_size==2)]

,retriever,k,qpp_method,window_size,alpha,r,p1(r),tau,p1(tau),num_of_queries
0,tct,10,spatial,2,0.0,0.033377,0.745518,0.017182,0.803104,97
1,tct,10,a_ratio,2,0.0,0.120325,0.240406,0.116838,0.089989,97
2,tct,10,nqc,2,0.0,0.137476,0.179334,0.105241,0.126721,97
3,tct,10,bertQPP,2,0.0,0.240609,0.017597,0.160653,0.019740,97
4,tct,10,bertQPP(QV),2,0.0,0.227438,0.025064,0.142182,0.039091,97

In [13]:
df[(df.alpha==1)&(df.qpp_method=='spatial')]

,retriever,k,qpp_method,window_size,alpha,r,p1(r),tau,p1(tau),num_of_queries
250,tct,10,spatial,2,1.0,0.370843,0.000185,0.243127,0.000419,97
505,tct,10,spatial,3,1.0,0.356591,0.000337,0.238402,0.000541,97
760,tct,10,spatial,4,1.0,0.350311,0.000435,0.228522,0.000913,97
1015,tct,10,spatial,5,1.0,0.314430,0.001709,0.194158,0.004841,97
1270,tct,10,spatial,6,1.0,0.292891,0.003598,0.182560,0.008069,97
1525,tct,10,spatial,7,1.0,0.339993,0.000656,0.235395,0.000636,97
1780,tct,10,spatial,8,1.0,0.323596,0.001224,0.226375,0.001020,97
2035,tct,10,spatial,9,1.0,0.251297,0.013032,0.161082,0.019414,97
2290,tct,10,spatial,10,1.0,0.259181,0.010362,0.167526,0.015058,97
2545,tct,10,spatial,11,1.0,0.275650,0.006280,0.162371,0.018464,97
2800,tct,10,spatial,12,1.0,0.269888,0.007508,0.153780,0.025647,97
3055,tct,10,spatial,13,1.0,0.270754,0.007311,0.194158,0.004841,97
3310,tct,10,spatial,14,1.0,0.266357,0.008361,0.192010,0.005332,97
3565,tct,10,spatial,15,1.0,0.286964,0.004374,0.189863,0.005867,97
3820,tct,10,spatial,16,1.0,0.268421,0.007853,0.186426,0.006825,97

In [291]:
df[(df.k==10)&(df.qpp_method=='nqc')].tau.values

array([], dtype=float64)